name: Java CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout project
        uses: actions/checkout@v3
        
      - name: Step 2 - Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
          cache: maven
          
      - name: Step 3 - Build with Maven
        run: mvn --batch-mode --update-snapshots package        
